FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

#Este es para que no moleste el ffmpeg
#Este es otro STEP porque este es otro RUN
# Actualizar las claves GPG antes de instalar ffmpeg
RUN apt-get update && apt-get install -y gnupg2 && \
    apt-key update && \
    apt-get update && apt-get install -y ffmpeg

COPY . .

ENV FLASK_APP=app.py

EXPOSE 5005

CMD ["flask", "run", "--host=0.0.0.0", "--port=5005", "--debug"]